#https://stackoverflow.com/questions/40905761/how-do-i-mount-a-host-directory-as-a-volume-in-docker-compose
FROM python:3
MAINTAINER mattc "contact@mattc.art"

VOLUME ["/app"]

WORKDIR /app
ADD requirements.txt /app
#RUN pip install -r requirements.txt \
	#&& pip install gunicorn
RUN pip install -r requirements.txt
#RUN pip install flask 
ENTRYPOINT ["python"]
CMD ["app.py"]

#CMD ["gunicorn", "app:app", "-b", "0.0.0.0:5000"]
